### PR TITLE
fix: fix sync test by use base enforcer's ClearPolicy and BuildRoleLink.

### LINKED ISSUE #190: [Test] Implementing unit tests for `SyncedEnforcer`
### Description

[Functional tests](https://github.com/casbin/casbin-cpp/blob/master/tests/enforcer_synced_test.cpp) for `casbin::SyncedEnforcer`. The problem arose due to ambiguity in handling multi-threaded tests in GoogleTest.

We need to inspect ways to get around this and implement it in our current test setup.

### Your System Info

NA

### Screenshots/Testimonials

NA

### PR DESCRIPTION
**Pull request by sheny1xuan**
Signed-off-by: stonex <1479765922@qq.com>

## Fixes #190 
+ I think the reason these test can't work may be the deadlock of policyMutex (lock it twice) in load policy.
+ Use base enforcer's ClearPolicy and BuildRoleLink.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@EmperorYP7

File: casbin/enforcer.cpp [hunk 1]
```diff
@@ -390,12 +390,13 @@ void Enforcer::ClearPolicy() {
 
 // LoadPolicy reloads the policy from file/database.
 void Enforcer::LoadPolicy() {
-    this->ClearPolicy();
+    // must use base's LoadPolicy to avoid dead lock
+    Enforcer::ClearPolicy();
```
Comment (EmperorYP7) [inline casbin/enforcer.cpp:394]: Good work on debugging!

**Review by EmperorYP7 — APPROVED** [review]
LGTM!
